#ifndef LIBSIGNELF_DEFINES_H__

#define SIGELF_NOTE_NAMESPACE   "SIGELF"
#define SIGELF_VER_NOTE         1
#define SIGELF_CERT_NOTE        2
#define SIGELF_SIG_NOTE         3
#define SIGELF_MANIFEST_NOTE    4
#define SIGELF_PROGRAM_ID_NOTE  5
#define SIGELF_NOTE_COUNT       6

#endif /* LIBSIGNELF_DEFINES_H__ */